# Generated by Django 3.0.8 on 2020-07-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatePoints',
            fields=[
                ('id', models.DateTimeField(primary_key=True, serialize=False, verbose_name='Id')),
                ('close', models.FloatField(verbose_name='Close')),
                ('sym', models.IntegerField(verbose_name='Symbol')),
            ],
        ),
        migrations.CreateModel(
            name='Symbols',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('sym', models.CharField(max_length=15, verbose_name='Symbol')),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'task', 'verbose_name_plural': 'tasks'},
        ),
    ]
